name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      
      - name: "Install XZC":
        run: |
          wget https://github.com/hellobertrand/zxc/releases/download/v0.10.0/zxc-linux-x86_64.tar.gz -O zxc.tar.gz
          tar -xzf zxc.tar.gz -C /usr/local

      - run: nimble install -Y
      - run: nim c src/zxc.nim
      - run: nimble test
