name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      
      - name: "Install XZC"
        run: |
          git clone https://github.com/hellobertrand/zxc.git zxclib
          cd zxclib
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel
          sudo cmake --install build

      - run: nimble install -Y
      - run: nim c src/zxc.nim
      - run: nimble test
